name: "Pupilfirst Reporting"
description: "Report test status for a submission in Pupilfirst LMS"
inputs:
  submission_data:
    description: Fields related to submission in JSON format
  report_file_path:
    description: Relative path of the report JSON file that holds the test data
  test_mode:
    description: Set to true for debugging
outputs:
  response: # output will be available to future steps
    description: "Response from the LMS"
runs:
  using: "node12"
  main: "dist/index.js"
